name: Packer Build
on:
  pull_request:
    # types:
    #   - closed
    branches:
      - main
jobs:
  build:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Enable mysql service
        run: sudo systemctl start mysql

      - name: Create .env File
        run: |
          echo "DB_NAME=${{ secrets.DB_NAME }}" > src/.env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> src/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> src/.env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> src/.env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> src/.env

      - name: Install Project Dependencies
        run: npm install
        working-directory: src

      - name: Wait for MySQL to be Ready
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Initialize MySQL Database as Root
        run: |
          sudo mysql -u"${{ secrets.DB_USERNAME }}" --password="${{ secrets.DB_PASSWORD }}" <<EOF
          CREATE DATABASE IF NOT EXISTS \`${{ secrets.DB_NAME }}\`;
          EOF

      - name: Run Tests
        run: npx jest
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
        working-directory: src

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # - name: Authenticate with Google Cloud
      #   uses: google-github-actions/auth@v2
      #   with:
      #     credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      # - name: Create JSON File from Secret
      #   run: |
      #     echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' | jq '.' > secret.json


      - name: Initialize Packer Plugins
        run: packer init -upgrade packer/

      - name: Build Custom Image
        id: build-ami
        run: |
          AMI_ID=$(packer build \
            -var "aws_region=${{ secrets.AWS_REGION }}" \
            -var "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
            -var "instance_type=t2.micro" \
            -var "ami_users=[\"${{ secrets.AMI_USERS }}\"]" \
            packer/ | grep -o 'ami-[0-9a-f]\{17\}' | tail -n 1)
          if [ -z "$AMI_ID" ]; then
            echo "Error: Failed to extract AMI ID from Packer output."
            exit 1
          fi
          echo "AMI ID: $AMI_ID"
          echo "ami-id=$AMI_ID" >> $GITHUB_OUTPUT
        env:
          PACKER_LOG: 1

      - name: Debug AMI ID
        run: |
          echo "AMI ID from build-ami: ${{ steps.build-ami.outputs.ami-id }}"
            
      # - name: Copy GCP Image to Demo Project
      #   env:
      #     GCP_ACCOUNT_ID: ${{ secrets.GCP_ACCOUNT_ID }}
      #     DEMO_GCP_ACCOUNT_ID: ${{ secrets.DEMO_GCP_ACCOUNT_ID }}
      #     IMAGE_NAME: ${{ secrets.GCP_IMAGE_NAME }}  
      #   run: |
      #     echo "Copying image from DEV ($GCP_ACCOUNT_ID) to DEMO ($DEMO_GCP_ACCOUNT_ID)..."
      #     gcloud compute images create "webapp-$(date +%s)" \
      #       --source-image="$IMAGE_NAME" \
      #       --source-image-project="$GCP_ACCOUNT_ID" \
      #       --project="$DEMO_GCP_ACCOUNT_ID" \
      #       --description="Copied from DEV on $(date)"

      - name: Configure AWS Credentials for Demo
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update Launch Template with New AMI
        id: update-lt
        run: |
          # Step 1: Retrieve Launch Template ID by filtering on name prefix
          LAUNCH_TEMPLATE_ID=$(aws ec2 describe-launch-templates \
            --filters "Name=launch-template-name,Values=csye6225_lt*" \
            --query "LaunchTemplates[0].LaunchTemplateId" \
            --output text)
          if [ -z "$LAUNCH_TEMPLATE_ID" ]; then
            echo "Error: Failed to retrieve the Launch Template ID for csye6225_lt*."
            exit 1
          fi
          echo "Launch Template ID: $LAUNCH_TEMPLATE_ID"
          echo "launch-template-id=$LAUNCH_TEMPLATE_ID" >> $GITHUB_OUTPUT

          # Step 2: Retrieve Latest Launch Template Version
          LATEST_VERSION=$(aws ec2 describe-launch-template-versions \
            --launch-template-id "$LAUNCH_TEMPLATE_ID" \
            --query "LaunchTemplateVersions[-1].VersionNumber" \
            --output text)
          if [ -z "$LATEST_VERSION" ]; then
            echo "Error: Failed to retrieve the latest version number for the Launch Template."
            exit 1
          fi
          echo "Latest Launch Template Version: $LATEST_VERSION"

          # Step 3: Create New Launch Template Version with New AMI
          NEW_VERSION=$(aws ec2 create-launch-template-version \
            --launch-template-id "$LAUNCH_TEMPLATE_ID" \
            --source-version "$LATEST_VERSION" \
            --launch-template-data "{\"ImageId\":\"${{ steps.build-ami.outputs.ami-id }}\"}" \
            --query "LaunchTemplateVersion.VersionNumber" \
            --output text)
          if [ -z "$NEW_VERSION" ]; then
            echo "Error: Failed to update the Launch Template with the new AMI."
            exit 1
          fi
          echo "New Launch Template Version: $NEW_VERSION"
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

          # Step 4: Set the New Version as Default
          aws ec2 modify-launch-template \
            --launch-template-id "$LAUNCH_TEMPLATE_ID" \
            --default-version "$NEW_VERSION"
          echo "Successfully updated the default Launch Template version to: $NEW_VERSION"
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Update Autoscaling Group
        run: |
          aws autoscaling update-auto-scaling-group \
            --auto-scaling-group-name csye6225_asg \
            --launch-template LaunchTemplateId=${{ steps.update-lt.outputs.launch-template-id }},Version=${{ steps.update-lt.outputs.version }}
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Trigger Instance Refresh
        id: refresh
        run: |
          REFRESH_ID=$(aws autoscaling start-instance-refresh \
            --auto-scaling-group-name csye6225_asg \
            --preferences '{"MinHealthyPercentage": 90}' \
            --query 'InstanceRefreshId' \
            --output text)
          echo "InstanceRefreshId=$REFRESH_ID" >> $GITHUB_OUTPUT
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Wait for Instance Refresh
        run: |
          while true; do
            STATUS=$(aws autoscaling describe-instance-refreshes \
              --auto-scaling-group-name csye6225_asg \
              --instance-refresh-ids ${{ steps.refresh.outputs.InstanceRefreshId }} \
              --query 'InstanceRefreshes[0].Status' \
              --output text)
            if [ "$STATUS" == "Successful" ] || [ "$STATUS" == "Failed" ]; then
              echo "Instance refresh completed with status: $STATUS"
              if [ "$STATUS" == "Failed" ]; then
                exit 1
              fi
              break
            fi
            echo "Waiting for instance refresh... Current status: $STATUS"
            sleep 30
          done
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}