name: CI - Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Jest Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=127.0.0.1 --user=testuser --password=testpassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x 

      - name: Install Node in VM
        run: apt install npm

      - name: Install Dependencies
        run: npm install

      - name: Wait for MySQL to be Ready
        run: |
          for i in {1..45}; do
            if mysqladmin ping -h 127.0.0.1 --user=testuser --password=testpassword --silent; then
              echo "MySQL is ready"
              exit 0
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done
          echo "MySQL did not start in time" >&2
          exit 1

      - name: Run Database Migrations (If Needed)
        run: npm run migrate

      - name: Run Tests
        run: npx jest
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USERNAME: testuser
          DB_PASSWORD: testpassword
          DB_NAME: testdb
