name: WebApp Unit Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        ports:
          - 3306:3306

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update and Install Dependencies
        run: sudo apt update && sudo apt install -y mysql-client

      - name: Create `.env` File
        run: |
          cat <<EOF > webapp/src/.env
          NODE_ENV=ci
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          PORT=${{ secrets.PORT }}
          EOF

      - name: Install Node.js Dependencies
        run: npm install
        working-directory: webapp/src

      - name: Wait for MySQL to Be Ready
        run: |
          echo "Waiting for MySQL to start..."
          for i in {30..0}; do
            if nc -z 127.0.0.1 3306; then
              echo "MySQL is up!"
              break
            fi
            echo "Still waiting for MySQL..."
            sleep 2
          done
          if [ "$i" = 0 ]; then
            echo "ERROR: MySQL failed to start"
            exit 1
          fi

      - name: Run Tests
        run: npx jest
        working-directory: webapp/src
