name: CI Workflow testing

on: [pull_request]

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    env:
      DB_HOST: 127.0.0.1
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${{ secrets.DB_PASSWORD }}';"
          sudo mysql -e "FLUSH PRIVILEGES;"

      - name: Configure MySQL
        run: |
          sudo mysql --user=root --password=${{ secrets.DB_PASSWORD }} --host=localhost --execute="
          CREATE USER IF NOT EXISTS '${{ secrets.DB_USERNAME }}'@'localhost' IDENTIFIED BY '${{ secrets.DB_PASSWORD }}';
          GRANT ALL PRIVILEGES ON *.* TO '${{ secrets.DB_USERNAME }}'@'localhost';
          CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_NAME }};
          FLUSH PRIVILEGES;"

      - name: Install Dependencies
        run: npm install
        working-directory: webapp/src  # Change this if your package.json is elsewhere

      - name: Run Tests
        run: npx jest
        working-directory: webapp/src  # Change this if tests are elsewhere
